export enum EstadoHabilitacion {
  DATOS_NEGOCIO = 'DATOS_NEGOCIO',
  ESPERANDO_TRAMITE_DIAN = 'ESPERANDO_TRAMITE_DIAN',
  RESOLUCION_CARGADA = 'RESOLUCION_CARGADA',
  TESTSET_EN_CURSO = 'TESTSET_EN_CURSO',
  HABILITADO = 'HABILITADO',
  ERROR = 'ERROR',
}
