export enum EstadoDocumentoElectronico {
  PENDIENTE = 'PENDIENTE',
  ACEPTADO = 'ACEPTADO',
  ACEPTADO_CON_OBSERVACIONES = 'ACEPTADO_CON_OBSERVACIONES',
  RECHAZADO = 'RECHAZADO',
  ERROR = 'ERROR',
}
