export enum TipoAlerta {
  STOCK_BAJO = 'STOCK_BAJO',
  CUOTA_POR_VENCER = 'CUOTA_POR_VENCER',
  CUOTA_VENCIDA = 'CUOTA_VENCIDA',
  CLIENTE_LIMITE_CREDITO = 'CLIENTE_LIMITE_CREDITO',
  VENTA_EN_MORA = 'VENTA_EN_MORA',
}

export enum SeveridadAlerta {
  BAJA = 'BAJA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
  CRITICA = 'CRITICA',
}
