export enum TipoVenta {
  CONTADO = 'CONTADO',
  CREDITO = 'CREDITO',
}

export enum EstadoVenta {
  ACTIVA = 'ACTIVA',
  PARCIALMENTE_PAGADA = 'PARCIALMENTE_PAGADA',
  COMPLETADA = 'COMPLETADA',
  VENCIDA = 'VENCIDA',
  EN_MORA = 'EN_MORA',
  CANCELADA = 'CANCELADA',
}
